project:
  type: website
  output-dir: docs
  resources:
    - files/**
    - images/**
    - projects/**

website:
  title: "CoastWatch West Code Node"
  favicon: images/coastwatch.png
  page-navigation: true

  navbar:
    logo: images/coastwatch_logo.png
    right:
      - text: " "
        href: index.qmd
      - text: "Data Access"
        menu:
          - text: Data Catalog
            href: data_catalog.qmd
          - text: Data Server
            href: data_server.qmd

      - text: "Tools and Training"
        menu:
          - text: Tools
            href: tools.qmd
          - text: Training
            href: training.qmd
          - text: Code Gallery
            href: code_gallery.qmd

      - text: "Applications"
        href: applications.qmd

      - text: "About"
        menu:
          - text: CoastWatch
            href: coastwatch.qmd
          - text: Contact Us
            href: contact_us.qmd
          - text: Customer Survey
            href: customer_survey.qmd
          - text: News Archive
            href: news_archive.qmd

format:
  html:
    theme: lux
    fontsize: 1.15em
    css: styles.css
    toc: true
    include-after-body: footer.html
    grid:
      body-width: 1100px

execute:
  echo: false
  warning: false
  error: false






